sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - cd module
  - sbt ++$TRAVIS_SCALA_VERSION compile && cd ../sample && sbt ++$TRAVIS_SCALA_VERSION test